# do not edit this file, please create a config_local.pl file which will
# be merged and overwrite settings from this file

use FindBin;
{
	debug => 1,
	log => {
		path => "$FindBin::RealBin/../../../cpan-api/var/log",
	}
}